Brings Azure object storage more inline with S3 and GCP.
Centeva/Centeva.ObjectStorage pull request #10
Opened 2023-09-11 14:02 UTC by maestro957

The injected storage service uses a Singleton to construct the appropriate storage class from the factory. Consequently, the storage parsing was not using the inherited class in Azure so the code would fail looking for azure://. Additionally, the parsing needs to not URL decode the connection string, but the variable to conditionally check that was not available at the appropriate level.

2023-09-11 14:48 UTC, pdeffendol requested changes
Boolean flags in public method signatures can frequently be considered a code smell.  It makes behavior harder to understand, and now that flag behavior has crept into more parts of the library.   I see that it was added in a previous PR, so I don't know the history behind it, but it may warrant a discussion.

2023-09-11 16:37 UTC, pdeffendol commented
Do we ever NOT want to URL-decode parts of the connection string?

2023-09-11 16:40 UTC, maestro957 commented
> Do we ever NOT want to URL-decode parts of the connection string?

Yes. The URL Decode is replacing the Base64 + with spaces and messing that up. I can change the Azure code to do a string replace on that field. Doing that would remove the necessity of having that Boolean parameter.

2023-09-11 17:16 UTC, pdeffendol requested changes

2023-09-11 17:16 UTC, pdeffendol commented on src/Centeva.ObjectStorage.Azure/AzureConnectionFactory.cs
> +            : (IObjectStorage)new AzureObjectStorage(connectionString);
This cast is not necessary?

2023-09-11 17:16 UTC, pdeffendol commented on src/Centeva.ObjectStorage.Azure/AzureObjectStorage.cs
> +    public AzureObjectStorage(ObjectStorageConnectionString? connectionString)
The other providers (Google, S3) deliberately did not allow the `ObjectStorageConnectionString` to be passed into their constructors.  Parsing the checking for required components was done in the factory classes.  Was there something preventing that from happening here?

2023-09-11 17:29 UTC, pdeffendol commented
> > Do we ever NOT want to URL-decode parts of the connection string?
> 
> Yes. The URL Decode is replacing the Base64 string '+' with spaces and messing that up. I can change the Azure code to do a string replace on that field. Doing that would remove the necessity of having that Boolean parameter.

In that case, change the `Parameters` in `ObjectStorageConnectionString` back to private as it was previously.

2023-09-11 18:44 UTC, pdeffendol commented on src/Centeva.ObjectStorage.Azure/AzureObjectStorage.cs
> +        var index = objectName.IndexOf('/');
You could potentially use `StoragePath.Split` here

2023-09-11 19:00 UTC, pdeffendol commented on src/Centeva.ObjectStorage.Azure/AzureObjectStorage.cs
> +        var index = objectName.IndexOf('/');
or not, it's a private method.  Needs more thought...

2023-09-12 14:35 UTC, pdeffendol approved these changes

2023-09-12 14:36 UTC, merged